test_form_authentication:
  url: "https://magento.softwaretestingboard.com/customer/account/login/"
  username: "dheerajjain60@gmail.com"
  password: "Jan@2012"
  expected: "https://magento.softwaretestingboard.com/"
test_form_search:
  searchFor: "yoga"
  url: "https://magento.softwaretestingboard.com/customer/account/login/"
  username: "dheerajjain60@gmail.com"
  password: "Jan@2012"
  expected: "https://magento.softwaretestingboard.com/"
test_form_search_page:
  searchFor: "yoga"
  url: "https://magento.softwaretestingboard.com/customer/account/login/"
